// Server-only: only ever imported via `await import()` from server functions
// in lib/items/store.ts, so `fs` never reaches a client bundle.
import fs from "node:fs";
import path from "node:path";
import type { CatalogItem } from "@/lib/items/types";

/**
 * Sandbox catalog loader. Active only when NEXT_PUBLIC_SANDBOX=1.
 *
 * Loads the ~3,191-item demo catalog generated by sandbox/build-catalog.mjs
 * from sandbox/catalog.json. Returns a single mutable in-memory array so the
 * admin demo (approve/reject/edit) reflects changes within a session WITHOUT
 * touching the real Supabase database or any payment path.
 *
 * Imported dynamically from lib/items/store.ts so this file (and `fs`) never
 * enters a client bundle or the normal production data path.
 */
let cache: CatalogItem[] | null = null;

export function getSandboxItems(): CatalogItem[] {
  if (cache) return cache;
  try {
    const raw = fs.readFileSync(path.join(process.cwd(), "sandbox", "catalog.json"), "utf8");
    cache = JSON.parse(raw) as CatalogItem[];
  } catch {
    cache = [];
  }
  return cache;
}

export function sandboxFind(sku: string): CatalogItem | undefined {
  return getSandboxItems().find((it) => it.sku === sku);
}

export function sandboxUpsert(item: CatalogItem): CatalogItem {
  const items = getSandboxItems();
  const i = items.findIndex((x) => x.sku === item.sku);
  if (i >= 0) items[i] = item;
  else items.unshift(item);
  return item;
}

export function sandboxDelete(sku: string): void {
  const items = getSandboxItems();
  const i = items.findIndex((x) => x.sku === sku);
  if (i >= 0) items.splice(i, 1);
}
