/**
 * Catalog seed — used to write `data/items.json` on first boot and to
 * keep the client bundle working without fs access.
 *
 * Pure data — safe to import from server, client, or edge.
 *
 * Heroes for the original test batch live in /test-images/. The newer
 * production photography (heroes + 2-3 scene variants per SKU) lives in
 * /catalog-images/. Every published item exposes a `gallery` array of
 * residential scene variants so the storefront item page can show real
 * context, not just the same hero on repeat.
 */
import type { CatalogItem } from "@/lib/items/types";

const CI = (sku: string, n: number) => `/catalog-images/${sku}-scene-${String(n).padStart(2, "0")}.jpg`;
const CIH = (sku: string) => `/catalog-images/${sku}-hero.jpg`;

export const SEED_ITEMS: CatalogItem[] = [
  // ============ DOORS (5) ============
  {
    id: "pl-d-101", sku: "PL-000101", brand: "priceless", category: "doors", status: "published",
    title: "Pre-Hung 5-Panel Interior Door",
    subtitle: "32\" × 80\" • Right-hand • Primed white shaker",
    price: 79, msrp: 189,
    image: "/test-images/01-interior-door-shaker.jpg",
    gallery: [CI("PL-000101", 1), CI("PL-000101", 2)],
    badges: ["Surplus", "New in crate"],
    manufacturer: "Masonite",
    dimensions: "32\" × 80\" × 1-3/8\"",
    weight: "47 lb",
    location: "Aisle D · Bay 4", inStock: 14,
  },
  {
    id: "pl-d-104", sku: "PL-000104", brand: "priceless", category: "doors", status: "published",
    title: "Reclaimed 5-Panel Solid Pine Door",
    subtitle: "30\" × 80\" • From 1920s Wausau farmhouse",
    price: 145,
    image: "/test-images/11-reclaimed-pine-door.jpg",
    gallery: [CI("PL-000104", 1), CI("PL-000104", 2)],
    badges: ["Reclaimed", "One-of-one"],
    manufacturer: "Salvage — Wausau, WI",
    dimensions: "30\" × 80\" × 1-3/4\"",
    weight: "62 lb",
    location: "Reclaim Loft", inStock: 1,
  },
  {
    id: "pl-d-110", sku: "PL-000110", brand: "priceless", category: "doors", status: "published",
    title: "Smooth Exterior Steel Door",
    subtitle: "36\" × 80\" • Pre-hung • Matte-black exterior",
    price: 199, msrp: 479,
    image: "/test-images/02-exterior-door-black-steel.jpg",
    gallery: [CI("PL-000110", 1), CI("PL-000110", 2)],
    badges: ["Surplus"],
    manufacturer: "JELD-WEN",
    dimensions: "36\" × 80\" × 1-3/4\"",
    weight: "88 lb",
    location: "Aisle D · Bay 1", inStock: 6,
  },
  {
    id: "pl-d-112", sku: "PL-000112", brand: "priceless", category: "doors", status: "published",
    title: "Pre-Hung French Double Door",
    subtitle: "60\" × 80\" • 3-lite divided • Painted white shaker",
    price: 419, msrp: 949,
    image: CIH("PL-000112"),
    gallery: [CI("PL-000112", 1), CI("PL-000112", 2)],
    badges: ["Surplus", "Cancelled order"],
    manufacturer: "Masonite",
    dimensions: "60\" × 80\" × 1-3/8\"",
    weight: "112 lb",
    location: "Aisle D · Bay 5", inStock: 2,
  },
  {
    id: "pl-d-115", sku: "PL-000115", brand: "priceless", category: "doors", status: "published",
    title: "Pocket-Door Slab + Track Kit",
    subtitle: "24\" × 80\" • Primed white • Includes hardware",
    price: 119, msrp: 269,
    image: CIH("PL-000115"),
    gallery: [CI("PL-000115", 1), CI("PL-000115", 2)],
    manufacturer: "Johnson Hardware",
    dimensions: "24\" × 80\" × 1-3/8\" (slab); 60\" track",
    weight: "42 lb",
    location: "Aisle D · Bay 6", inStock: 5,
  },

  // ============ WINDOWS (5) ============
  {
    id: "pl-w-201", sku: "PL-000201", brand: "priceless", category: "windows", status: "published",
    title: "Vinyl Double-Hung Window",
    subtitle: "36\" × 60\" • Low-E • White vinyl",
    price: 129, msrp: 329,
    image: "/test-images/06-double-hung-window.jpg",
    gallery: [CI("PL-000201", 1), CI("PL-000201", 2)],
    badges: ["Energy Star"],
    manufacturer: "ReliaBilt",
    dimensions: "36\" × 60\"",
    weight: "54 lb",
    location: "Aisle W · Bay 2", inStock: 22,
  },
  {
    id: "pl-w-208", sku: "PL-000208", brand: "priceless", category: "windows", status: "published",
    title: "Black-Frame Casement Window",
    subtitle: "24\" × 48\" • Crank-out • Tempered glass",
    price: 219, msrp: 549,
    image: "/test-images/12-black-casement-window.jpg",
    gallery: [CI("PL-000208", 1), CI("PL-000208", 2)],
    manufacturer: "Andersen 100 Series",
    dimensions: "24\" × 48\"",
    weight: "61 lb",
    location: "Aisle W · Bay 5", inStock: 4,
  },
  {
    id: "pl-w-211", sku: "PL-000211", brand: "priceless", category: "windows", status: "published",
    title: "Vinyl Awning Window",
    subtitle: "36\" × 24\" • Crank-out • Low-E insulated",
    price: 159, msrp: 369,
    image: CIH("PL-000211"),
    gallery: [CI("PL-000211", 1), CI("PL-000211", 2)],
    badges: ["Energy Star"],
    manufacturer: "ReliaBilt",
    dimensions: "36\" × 24\"",
    weight: "38 lb",
    location: "Aisle W · Bay 3", inStock: 11,
  },
  {
    id: "pl-w-214", sku: "PL-000214", brand: "priceless", category: "windows", status: "published",
    title: "Large Picture Window, Black Frame",
    subtitle: "72\" × 60\" • Fixed • Slim aluminum • Low-E",
    price: 689, msrp: 1499,
    image: CIH("PL-000214"),
    gallery: [CI("PL-000214", 1), CI("PL-000214", 2)],
    badges: ["Surplus"],
    manufacturer: "Marvin Essential",
    dimensions: "72\" × 60\"",
    weight: "168 lb",
    location: "Aisle W · Bay 7", inStock: 1,
  },
  {
    id: "pl-w-219", sku: "PL-000219", brand: "priceless", category: "windows", status: "published",
    title: "3-Panel Vinyl Sliding Patio Door",
    subtitle: "108\" × 80\" • Center panel slides • White vinyl",
    price: 949, msrp: 2199,
    image: CIH("PL-000219"),
    gallery: [CI("PL-000219", 1), CI("PL-000219", 2)],
    badges: ["Surplus", "New in crate"],
    manufacturer: "JELD-WEN",
    dimensions: "108\" × 80\"",
    weight: "242 lb",
    location: "Aisle W · Bay 8", inStock: 1,
  },

  // ============ CABINETS (5 priceless + 2 builders) ============
  {
    id: "pl-c-301", sku: "PL-000301", brand: "priceless", category: "cabinets", status: "published",
    title: "30\" White Shaker Base Cabinet",
    subtitle: "Full overlay • Soft-close • Solid wood face",
    price: 189, msrp: 419,
    image: "/test-images/03-base-cabinet-white-shaker.jpg",
    gallery: [CI("PL-000301", 1), CI("PL-000301", 2)],
    manufacturer: "ProSource",
    dimensions: "30\" W × 34-1/2\" H × 24\" D",
    weight: "78 lb",
    location: "Aisle C · Bay 3", inStock: 9,
  },
  {
    id: "pl-c-305", sku: "PL-000305", brand: "priceless", category: "cabinets", status: "published",
    title: "36\" Espresso Wall Cabinet",
    subtitle: "30\" tall • Two doors • Adjustable shelves",
    price: 159, msrp: 359,
    image: "/test-images/13-espresso-wall-cabinet.jpg",
    gallery: [CI("PL-000305", 1), CI("PL-000305", 2)],
    manufacturer: "ProSource",
    dimensions: "36\" W × 30\" H × 12\" D",
    weight: "54 lb",
    location: "Aisle C · Bay 4", inStock: 11,
  },
  {
    id: "pl-c-311", sku: "PL-000311", brand: "priceless", category: "cabinets", status: "published",
    title: "36\" White Shaker Sink Base",
    subtitle: "Two doors • False drawer front • Plumbing knockouts",
    price: 219, msrp: 489,
    image: CIH("PL-000311"),
    gallery: [CI("PL-000311", 1), CI("PL-000311", 2)],
    manufacturer: "ProSource",
    dimensions: "36\" W × 34-1/2\" H × 24\" D",
    weight: "88 lb",
    location: "Aisle C · Bay 3", inStock: 6,
  },
  {
    id: "bc-c-801", sku: "BC-000801", brand: "builders", category: "cabinets", status: "published",
    title: "Custom White-Oak Shaker Run",
    subtitle: "Made-to-order • Conestoga box • 10-year warranty",
    price: 14800,
    image: "/test-images/17-whiteoak-shaker-kitchen.jpg",
    gallery: [CI("BC-000801", 1), CI("BC-000801", 2)],
    badges: ["Custom"],
    manufacturer: "Conestoga Wood Specialties",
    location: "Builders Corner Showroom", inStock: 0,
  },
  {
    id: "bc-c-802", sku: "BC-000802", brand: "builders", category: "cabinets", status: "published",
    title: "Bone-White Inset Painted Kitchen",
    subtitle: "Furniture-grade inset • Hand-painted • 5-piece doors",
    price: 22400,
    image: "/test-images/18-bone-white-inset-kitchen.jpg",
    gallery: [CI("BC-000802", 1), CI("BC-000802", 2)],
    badges: ["Custom", "Designer pick"],
    manufacturer: "Conestoga Wood Specialties",
    location: "Builders Corner Showroom", inStock: 0,
  },

  // ============ VANITIES (5) ============
  {
    id: "pl-v-401", sku: "PL-000401", brand: "priceless", category: "vanities", status: "published",
    title: "48\" Single-Sink Vanity, Quartz Top",
    subtitle: "Soft-close • White shaker • Brushed nickel pulls",
    price: 449, msrp: 1099,
    image: "/test-images/14-white-vanity-quartz.jpg",
    gallery: [CI("PL-000401", 1), CI("PL-000401", 2)],
    badges: ["Showroom favorite"],
    manufacturer: "Allen + Roth",
    dimensions: "48\" W × 34\" H × 22\" D",
    weight: "168 lb",
    location: "Showroom · West Wall", inStock: 3,
  },
  {
    id: "pl-v-404", sku: "PL-000404", brand: "priceless", category: "vanities", status: "published",
    title: "30\" Floating Walnut Vanity",
    subtitle: "Wall-mount • Integrated porcelain basin • Brushed brass",
    price: 379, msrp: 899,
    image: CIH("PL-000404"),
    gallery: [CI("PL-000404", 1), CI("PL-000404", 2)],
    manufacturer: "James Martin Signature",
    dimensions: "30\" W × 20\" H × 19\" D",
    weight: "98 lb",
    location: "Showroom · East Wall", inStock: 2,
  },
  {
    id: "pl-v-409", sku: "PL-000409", brand: "priceless", category: "vanities", status: "published",
    title: "60\" Double-Sink Sage Vanity",
    subtitle: "Polished quartz top • Three center drawers • Chrome faucets",
    price: 899, msrp: 2199,
    image: CIH("PL-000409"),
    gallery: [CI("PL-000409", 1), CI("PL-000409", 2)],
    badges: ["Showroom favorite"],
    manufacturer: "Allen + Roth",
    dimensions: "60\" W × 34\" H × 22\" D",
    weight: "232 lb",
    location: "Showroom · West Wall", inStock: 1,
  },
  {
    id: "pl-v-412", sku: "PL-000412", brand: "priceless", category: "vanities", status: "published",
    title: "24\" European Floating Vanity",
    subtitle: "Matte-white slab • Integrated stone basin • Wall-mount",
    price: 249, msrp: 599,
    image: CIH("PL-000412"),
    gallery: [CI("PL-000412", 1), CI("PL-000412", 2)],
    manufacturer: "Eviva",
    dimensions: "24\" W × 20\" H × 18\" D",
    weight: "62 lb",
    location: "Showroom · East Wall", inStock: 4,
  },
  {
    id: "pl-v-415", sku: "PL-000415", brand: "priceless", category: "vanities", status: "published",
    title: "Classic Pedestal Sink, Chrome Faucet",
    subtitle: "Vitreous china • Faucet included • Period-correct",
    price: 169, msrp: 389,
    image: CIH("PL-000415"),
    gallery: [CI("PL-000415", 1), CI("PL-000415", 2)],
    manufacturer: "Kohler Memoirs",
    dimensions: "22\" W × 34\" H × 18\" D",
    weight: "78 lb",
    location: "Showroom · East Wall", inStock: 5,
  },

  // ============ COUNTERTOPS (4 priceless + 1 builders) ============
  {
    id: "pl-co-810", sku: "PL-000810", brand: "priceless", category: "countertops", status: "published",
    title: "Maple Butcher-Block Countertop, 8 ft",
    subtitle: "96\" × 25\" × 1-1/2\" • Edge-grain hard maple • Natural finish",
    price: 269, msrp: 569,
    image: CIH("PL-000810"),
    gallery: [CI("PL-000810", 1), CI("PL-000810", 2)],
    manufacturer: "John Boos",
    dimensions: "96\" × 25\" × 1-1/2\"",
    weight: "112 lb",
    location: "Slab Yard", inStock: 4,
  },
  {
    id: "pl-co-812", sku: "PL-000812", brand: "priceless", category: "countertops", status: "published",
    title: "Granite Remnant, Polished Grey",
    subtitle: "36\" × 30\" × 3cm • Soft grey with speckle • Polished edge",
    price: 219, msrp: 489,
    image: CIH("PL-000812"),
    gallery: [CI("PL-000812", 1), CI("PL-000812", 2)],
    badges: ["Remnant", "One-of-one"],
    manufacturer: "MSI Surfaces",
    dimensions: "36\" × 30\" × 3cm",
    weight: "84 lb",
    location: "Slab Yard · Remnant Rack", inStock: 1,
  },
  {
    id: "pl-co-815", sku: "PL-000815", brand: "priceless", category: "countertops", status: "published",
    title: "Honed Soapstone Slab, 5 ft",
    subtitle: "60\" × 25\" × 3cm • Charcoal with pale veining • Honed finish",
    price: 549, msrp: 1199,
    image: CIH("PL-000815"),
    gallery: [CI("PL-000815", 1), CI("PL-000815", 2)],
    manufacturer: "Dorado Soapstone",
    dimensions: "60\" × 25\" × 3cm",
    weight: "168 lb",
    location: "Slab Yard", inStock: 2,
  },
  {
    id: "pl-co-819", sku: "PL-000819", brand: "priceless", category: "countertops", status: "published",
    title: "Walnut End-Grain Butcher Block, 6 ft",
    subtitle: "72\" × 25\" × 1-3/4\" • Solid walnut • Oil finish",
    price: 449, msrp: 949,
    image: CIH("PL-000819"),
    gallery: [CI("PL-000819", 1), CI("PL-000819", 2)],
    badges: ["Showroom favorite"],
    manufacturer: "John Boos",
    dimensions: "72\" × 25\" × 1-3/4\"",
    weight: "118 lb",
    location: "Slab Yard", inStock: 2,
  },
  {
    id: "bc-co-803", sku: "BC-000803", brand: "builders", category: "countertops", status: "published",
    title: "Calacatta Quartz Slab",
    subtitle: "126\" × 63\" • Polished • 3cm",
    price: 2200,
    image: "/test-images/19-calacatta-quartz-slab.jpg",
    gallery: [CI("BC-000803", 1), CI("BC-000803", 2)],
    manufacturer: "Caesarstone",
    dimensions: "126\" × 63\" × 3cm",
    weight: "412 lb",
    location: "Slab Yard", inStock: 2,
  },

  // ============ HARDWARE (5) ============
  {
    id: "pl-h-501", sku: "PL-000501", brand: "priceless", category: "hardware", status: "published",
    title: "Matte Black Cabinet Pulls (10-pack)",
    subtitle: "5\" center-to-center • Solid zinc",
    price: 24, msrp: 49,
    image: "/test-images/15-matte-black-pulls.jpg",
    gallery: [CI("PL-000501", 1), CI("PL-000501", 2)],
    manufacturer: "Amerock",
    dimensions: "5\" CC bar pulls",
    weight: "1.4 lb (pack)",
    location: "Bin H-12", inStock: 48,
  },
  {
    id: "pl-h-510", sku: "PL-000510", brand: "priceless", category: "hardware", status: "published",
    title: "Polished Brass Round Knobs (5-pack)",
    subtitle: "1-1/4\" diameter • Solid brass",
    price: 19, msrp: 39,
    image: CIH("PL-000510"),
    gallery: [CI("PL-000510", 1), CI("PL-000510", 2)],
    manufacturer: "Schaub & Co.",
    dimensions: "1-1/4\" Ø round knob",
    weight: "0.6 lb (pack)",
    location: "Bin H-14", inStock: 36,
  },
  {
    id: "pl-h-513", sku: "PL-000513", brand: "priceless", category: "hardware", status: "published",
    title: "Satin Nickel Modern Bar Pulls (10-pack)",
    subtitle: "4\" center-to-center • Solid zinc with satin nickel finish",
    price: 22, msrp: 47,
    image: CIH("PL-000513"),
    gallery: [CI("PL-000513", 1), CI("PL-000513", 2)],
    manufacturer: "Amerock",
    dimensions: "4\" CC bar pulls",
    weight: "1.2 lb (pack)",
    location: "Bin H-12", inStock: 52,
  },
  {
    id: "pl-h-516", sku: "PL-000516", brand: "priceless", category: "hardware", status: "published",
    title: "Polished Chrome Bin Pulls (8-pack)",
    subtitle: "3\" center-to-center • Traditional cup-style",
    price: 26, msrp: 54,
    image: CIH("PL-000516"),
    gallery: [CI("PL-000516", 1), CI("PL-000516", 2)],
    manufacturer: "Top Knobs",
    dimensions: "3\" CC bin pulls",
    weight: "1.1 lb (pack)",
    location: "Bin H-13", inStock: 28,
  },
  {
    id: "pl-h-519", sku: "PL-000519", brand: "priceless", category: "hardware", status: "published",
    title: "Vintage Glass + Brass Knobs (6-pack)",
    subtitle: "1-1/4\" cut-glass face • Polished brass base",
    price: 32, msrp: 69,
    image: CIH("PL-000519"),
    gallery: [CI("PL-000519", 1), CI("PL-000519", 2)],
    badges: ["Specialty"],
    manufacturer: "House of Antique Hardware",
    dimensions: "1-1/4\" Ø glass knob",
    weight: "0.8 lb (pack)",
    location: "Bin H-15", inStock: 14,
  },

  // ============ LIGHTING (5) ============
  {
    id: "pl-l-601", sku: "PL-000601", brand: "priceless", category: "lighting", status: "published",
    title: "3-Light Brushed-Brass Vanity Bar",
    subtitle: "24\" • E26 base • Damp-rated",
    price: 79, msrp: 189,
    image: "/test-images/16-brass-vanity-bar.jpg",
    gallery: [CI("PL-000601", 1), CI("PL-000601", 2)],
    manufacturer: "Hinkley Lighting",
    dimensions: "24\" L × 6\" H × 7\" D",
    weight: "5.4 lb",
    location: "Aisle L · Bay 1", inStock: 7,
  },
  {
    id: "pl-l-605", sku: "PL-000605", brand: "priceless", category: "lighting", status: "published",
    title: "36\" Matte-Black Linear Pendant",
    subtitle: "Integrated LED • 3000K • 2400 lm",
    price: 149, msrp: 329,
    image: CIH("PL-000605"),
    gallery: [CI("PL-000605", 1), CI("PL-000605", 2)],
    manufacturer: "Kichler",
    dimensions: "36\" L × 4\" H × 4\" D",
    weight: "7.2 lb",
    location: "Aisle L · Bay 2", inStock: 4,
  },
  {
    id: "pl-l-609", sku: "PL-000609", brand: "priceless", category: "lighting", status: "published",
    title: "4-Light Antique-Brass Cluster Pendant",
    subtitle: "Clear glass globes • Staggered cords • E26",
    price: 189, msrp: 449,
    image: CIH("PL-000609"),
    gallery: [CI("PL-000609", 1), CI("PL-000609", 2)],
    manufacturer: "Hinkley Lighting",
    dimensions: "18\" Ø canopy • 48\" max drop",
    weight: "9.6 lb",
    location: "Aisle L · Bay 3", inStock: 3,
  },
  {
    id: "pl-l-612", sku: "PL-000612", brand: "priceless", category: "lighting", status: "published",
    title: "Brushed-Brass Swing-Arm Sconces (pair)",
    subtitle: "Linen drum shades • Hardwired • Pair",
    price: 159, msrp: 369,
    image: CIH("PL-000612"),
    gallery: [CI("PL-000612", 1), CI("PL-000612", 2)],
    manufacturer: "Visual Comfort",
    dimensions: "Each: 22\" arm extension × 6\" Ø shade",
    weight: "4.8 lb (pair)",
    location: "Aisle L · Bay 4", inStock: 2,
  },
  {
    id: "pl-l-616", sku: "PL-000616", brand: "priceless", category: "lighting", status: "published",
    title: "Matte-Black Up-Light Wall Sconce",
    subtitle: "Frosted cylinder shade • Damp-rated • E26",
    price: 49, msrp: 109,
    image: CIH("PL-000616"),
    gallery: [CI("PL-000616", 1), CI("PL-000616", 2)],
    manufacturer: "Kichler",
    dimensions: "5\" W × 12\" H × 4\" D",
    weight: "2.1 lb",
    location: "Aisle L · Bay 5", inStock: 14,
  },

  // ============ TRIM (5) ============
  {
    id: "pl-t-701", sku: "PL-000701", brand: "priceless", category: "trim", status: "published",
    title: "Primed MDF Base Trim (8-pc bundle)",
    subtitle: "5-1/4\" × 8' • Smooth finish",
    price: 39, msrp: 89,
    image: "/test-images/08-painted-trim-stack.jpg",
    gallery: [CI("PL-000701", 1), CI("PL-000701", 2)],
    manufacturer: "Metrie",
    dimensions: "5-1/4\" face × 8 ft (×8 pcs)",
    weight: "62 lb (bundle)",
    location: "Trim Rack 2", inStock: 32,
  },
  {
    id: "pl-t-704", sku: "PL-000704", brand: "priceless", category: "trim", status: "published",
    title: "Primed Crown Molding Bundle, 8 ft × 8",
    subtitle: "4-5/8\" ogee • Solid wood • Factory primed",
    price: 64, msrp: 139,
    image: CIH("PL-000704"),
    gallery: [CI("PL-000704", 1), CI("PL-000704", 2)],
    manufacturer: "Metrie",
    dimensions: "4-5/8\" face × 8 ft (×8 pcs)",
    weight: "48 lb (bundle)",
    location: "Trim Rack 3", inStock: 18,
  },
  {
    id: "pl-t-708", sku: "PL-000708", brand: "priceless", category: "trim", status: "published",
    title: "Primed Door + Window Casing (10-pc)",
    subtitle: "2-1/4\" face × 8 ft • Beaded edge • MDF",
    price: 32, msrp: 79,
    image: CIH("PL-000708"),
    gallery: [CI("PL-000708", 1), CI("PL-000708", 2)],
    manufacturer: "Metrie",
    dimensions: "2-1/4\" face × 8 ft (×10 pcs)",
    weight: "42 lb (bundle)",
    location: "Trim Rack 2", inStock: 26,
  },
  {
    id: "pl-t-712", sku: "PL-000712", brand: "priceless", category: "trim", status: "published",
    title: "Primed Shoe Molding (20-pc bundle)",
    subtitle: "3/4\" × 1/2\" × 8 ft • Solid pine • Primed",
    price: 28, msrp: 62,
    image: CIH("PL-000712"),
    gallery: [CI("PL-000712", 1), CI("PL-000712", 2)],
    manufacturer: "Metrie",
    dimensions: "3/4\" × 1/2\" × 8 ft (×20 pcs)",
    weight: "28 lb (bundle)",
    location: "Trim Rack 1", inStock: 22,
  },
  {
    id: "pl-t-716", sku: "PL-000716", brand: "priceless", category: "trim", status: "published",
    title: "Primed Chair-Rail Molding (8-pc bundle)",
    subtitle: "2-5/8\" face × 8 ft • Stepped profile • MDF",
    price: 42, msrp: 94,
    image: CIH("PL-000716"),
    gallery: [CI("PL-000716", 1), CI("PL-000716", 2)],
    manufacturer: "Metrie",
    dimensions: "2-5/8\" face × 8 ft (×8 pcs)",
    weight: "38 lb (bundle)",
    location: "Trim Rack 3", inStock: 12,
  },
];
