// AUTO-GENERATED by tools/x5-frames/emit_showcase.py from the store
// walkthrough. Shows WHAT'S ON THE FLOOR at honest, conservative scale —
// not product listings. Depth estimates are de-overlapped and rounded down.

export interface Collection {
  name: string;
  tier: string;     // "A full wall" | "Hundreds" | "Dozens" | ...
  approx: string;   // conservative "N+" or "" 
  kind: string;
  brands: string[];
}
export const STORE_SHOWCASE: Record<string, Collection[]> = {
 "Trim & Molding": [
  {
   "name": "Trim & profiles",
   "tier": "A full wall",
   "approx": "1300+",
   "kind": "pieces",
   "brands": [
    "Asd",
    "Badger",
    "Frontline Bldg. Products Inc.",
    "Lawrence Brothers",
    "The Temple Company"
   ]
  },
  {
   "name": "Edge banding & veneer",
   "tier": "Stocked deep",
   "approx": "20+",
   "kind": "rolls",
   "brands": []
  },
  {
   "name": "Base shoe & molding",
   "tier": "Thousands of feet",
   "approx": "",
   "kind": "feet",
   "brands": [
    "Grip-Rite"
   ]
  }
 ],
 "Doors": [
  {
   "name": "Exterior & entry doors",
   "tier": "Dozens",
   "approx": "100+",
   "kind": "doors",
   "brands": [
    "Badger",
    "Kwikset",
    "Manion'S",
    "Superdeck"
   ]
  },
  {
   "name": "Interior door slabs",
   "tier": "A full wall",
   "approx": "600+",
   "kind": "doors",
   "brands": [
    "Badger",
    "Bella Quartz",
    "Global Point",
    "Integra",
    "Lynden Door",
    "Premdor"
   ]
  },
  {
   "name": "Glass-panel & French doors",
   "tier": "Dozens",
   "approx": "50+",
   "kind": "doors",
   "brands": [
    "Badger",
    "Utilitech",
    "Wolf"
   ]
  },
  {
   "name": "Patio & sliding doors",
   "tier": "Stocked deep",
   "approx": "40+",
   "kind": "doors",
   "brands": [
    "Andersen",
    "Cox",
    "Jeld-Wen",
    "Johnson",
    "Johnson Hardware",
    "Lawrence"
   ]
  },
  {
   "name": "Pre-hung doors",
   "tier": "Stocked deep",
   "approx": "40+",
   "kind": "doors",
   "brands": [
    "Badger",
    "Dura-Frame",
    "Global Point",
    "Masonite",
    "Shuster'S",
    "Western"
   ]
  },
  {
   "name": "Bifold doors",
   "tier": "Stocked deep",
   "approx": "30+",
   "kind": "doors",
   "brands": [
    "Cox",
    "Lynden Door",
    "Maywood",
    "Premdor",
    "Steves"
   ]
  }
 ],
 "Railing": [
  {
   "name": "Balusters & spindles",
   "tier": "A full wall",
   "approx": "600+",
   "kind": "pieces",
   "brands": []
  },
  {
   "name": "Newel posts",
   "tier": "Dozens",
   "approx": "50+",
   "kind": "posts",
   "brands": []
  },
  {
   "name": "Handrail & brackets",
   "tier": "Stocked deep",
   "approx": "30+",
   "kind": "pieces",
   "brands": [
    "Afco",
    "Trex",
    "Trex Signature",
    "Westbury"
   ]
  }
 ],
 "Windows": [
  {
   "name": "Casement & vinyl windows",
   "tier": "A full wall",
   "approx": "500+",
   "kind": "windows",
   "brands": [
    "Alcoa",
    "Compass",
    "Everlife",
    "Floort\u00e9",
    "Jeld-Wen",
    "Msi"
   ]
  },
  {
   "name": "Wood-framed windows",
   "tier": "Stocked deep",
   "approx": "20+",
   "kind": "windows",
   "brands": [
    "Norco"
   ]
  },
  {
   "name": "Arched & specialty windows",
   "tier": "Stocked deep",
   "approx": "50+",
   "kind": "windows",
   "brands": [
    "Ingersoll-Rand",
    "Jeld-Wen",
    "Magna-Frame",
    "Vetter"
   ]
  },
  {
   "name": "Double-hung windows",
   "tier": "Stocked deep",
   "approx": "30+",
   "kind": "windows",
   "brands": [
    "Alcoa",
    "Andersen",
    "Badger",
    "Jeld-Wen",
    "Polaris"
   ]
  }
 ],
 "Paint & Supplies": [
  {
   "name": "Paint & stain",
   "tier": "A full wall",
   "approx": "500+",
   "kind": "cans",
   "brands": [
    "Best Look",
    "Fusion",
    "Fusion Mineral Paint",
    "Lenmar",
    "Milk Paint",
    "Minwax"
   ]
  }
 ],
 "Hardware": [
  {
   "name": "Locksets & door hardware",
   "tier": "Hundreds",
   "approx": "300+",
   "kind": "pieces",
   "brands": [
    "Amerock",
    "Countryside Cabinets",
    "Ideal",
    "Ideal Security",
    "Kwikset",
    "Schlage"
   ]
  },
  {
   "name": "Hinges & specialty hardware",
   "tier": "Hundreds",
   "approx": "200+",
   "kind": "pieces",
   "brands": [
    "Amerock",
    "Blum",
    "Ives",
    "Soss"
   ]
  },
  {
   "name": "Cabinet knobs & pulls",
   "tier": "Hundreds",
   "approx": "250+",
   "kind": "pieces",
   "brands": [
    "Amerock",
    "Design House",
    "Home Collection",
    "Lockset",
    "Titan"
   ]
  },
  {
   "name": "Garage door parts",
   "tier": "Stocked deep",
   "approx": "50+",
   "kind": "pieces",
   "brands": []
  },
  {
   "name": "Electrical boxes & supplies",
   "tier": "Stocked deep",
   "approx": "40+",
   "kind": "pieces",
   "brands": [
    "Leviton",
    "Slater"
   ]
  }
 ],
 "Cabinets": [
  {
   "name": "Base cabinets",
   "tier": "Stocked deep",
   "approx": "50+",
   "kind": "cabinets",
   "brands": [
    "Bella Quartz"
   ]
  },
  {
   "name": "Cabinet doors & parts",
   "tier": "Dozens",
   "approx": "75+",
   "kind": "cabinets",
   "brands": [
    "Showplace",
    "Wolf",
    "Wolf Artisan"
   ]
  },
  {
   "name": "Wall & upper cabinets",
   "tier": "Stocked deep",
   "approx": "40+",
   "kind": "cabinets",
   "brands": []
  },
  {
   "name": "Pantry & tall cabinets",
   "tier": "In stock",
   "approx": "",
   "kind": "cabinets",
   "brands": []
  }
 ],
 "Lighting": [
  {
   "name": "Chandeliers & pendants",
   "tier": "Dozens",
   "approx": "125+",
   "kind": "fixtures",
   "brands": [
    "Home Decorators Collection",
    "Patriot Lighting"
   ]
  },
  {
   "name": "Vanity & ceiling fixtures",
   "tier": "Stocked deep",
   "approx": "20+",
   "kind": "fixtures",
   "brands": []
  },
  {
   "name": "Ceiling fans",
   "tier": "In stock",
   "approx": "",
   "kind": "fixtures",
   "brands": []
  }
 ],
 "Sinks & Plumbing": [
  {
   "name": "Toilets & fixtures",
   "tier": "Stocked deep",
   "approx": "30+",
   "kind": "pieces",
   "brands": [
    "Delta",
    "Kohler",
    "Newport Brass"
   ]
  },
  {
   "name": "Kitchen & bath sinks",
   "tier": "Stocked deep",
   "approx": "30+",
   "kind": "sinks",
   "brands": []
  },
  {
   "name": "Vessel sinks",
   "tier": "In stock",
   "approx": "",
   "kind": "sinks",
   "brands": []
  }
 ],
 "Vanities": [
  {
   "name": "Bathroom vanities",
   "tier": "Dozens",
   "approx": "100+",
   "kind": "vanities",
   "brands": [
    "Patriot Lighting"
   ]
  }
 ],
 "Countertops": [
  {
   "name": "Laminate & butcher block",
   "tier": "Stocked deep",
   "approx": "40+",
   "kind": "slabs",
   "brands": []
  },
  {
   "name": "Quartz & granite tops",
   "tier": "Stocked deep",
   "approx": "20+",
   "kind": "slabs",
   "brands": [
    "Bella Quartz",
    "Bello Quartz",
    "Cut In Stone",
    "Cut In Stone Llc",
    "Msi",
    "Shaw Floors"
   ]
  }
 ]
};

export const SHOWCASE_DEPARTMENTS = ["Trim & Molding", "Doors", "Railing", "Windows", "Paint & Supplies", "Hardware", "Cabinets", "Lighting", "Sinks & Plumbing", "Vanities", "Countertops"];
