// AUTO-GENERATED by tools/x5-frames/fetch_logos.py + manual QA.
// Slugs with a verified-correct local logo in public/vendor-logos/.
// Vendors not listed here render as a clean text chip.
export const VENDOR_LOGOS = new Set<string>(["alcoa", "amerock", "andersen", "blum", "chamberlain", "delta", "duravit", "grip-rite", "home-decorators-collection", "ingersoll-rand", "irwin", "jeld-wen", "johnson-hardware", "koch-cabinets", "kohler", "kwikset", "leviton", "loctite", "lynden-door", "m-d-building-products", "marvin", "masonite", "newport-brass", "pella", "quikrete", "samuel-heath", "schlage", "showplace-cabinetry", "simpson-strong-tie", "soss", "steves-sons", "therma-tru", "trex", "velux", "western-building-products"]);
